APP_NAME = "ModChatBot"

FOOTER_HTML = f"""
<style>
    .footer {{
        position: fixed;
        left: 10%;
        bottom: 0;
        width: 100%;
        color: gray;
        text-align: center;
        padding: 15px;
        font-size: small;
        z-index: 1000;
    }}
    /* Make space for the footer */
    .stApp {{
        padding-bottom: 20px;
    }}
    .footer p {{
        font-style: italic;
        font-size: small;
    }}
</style>
<div class="footer">
    <p>Responses are generated by AI. Make sure to check for accuracy</p>
</div>
"""


