ARG BASE_IMAGE=python:3.10-slim-buster
FROM $BASE_IMAGE
COPY modweeklyinsights/requirements.txt /tmp/requirements.txt
RUN pip install --upgrade pip && \
    pip install -r /tmp/requirements.txt
COPY modweeklyinsights /app/modweeklyinsights
ENV PYTHONPATH=/app
WORKDIR /apps
COPY common_app_files /app/common_app_files
COPY project_path.py /app/project_path.py
RUN chmod +x /app/modweeklyinsights/entrypoint.sh
EXPOSE 8501
CMD ["/app/modweeklyinsights/entrypoint.sh"]