ARG BASE_IMAGE=python:3.10-slim-buster
FROM $BASE_IMAGE
COPY mod_review/requirements.txt /tmp/requirements.txt
RUN pip install --upgrade pip && \
    pip install -r /tmp/requirements.txt
COPY mod_review /app/mod_review
ENV PYTHONPATH=/app
WORKDIR /apps
COPY common_app_files /app/common_app_files
COPY project_path.py /app/project_path.py
RUN chmod +x /app/mod_review/entrypoint.sh
EXPOSE 8501
CMD ["/app/mod_review/entrypoint.sh"]