
overview_markdown = """ 
### Welcome to ModAnalytics

- Empower Your Data with OpenAI’s Advanced Assistants and Code Interpreter: Execute Python code in a secure environment for comprehensive data analysis. Upload datasets in multiple formats, perform detailed analyses, and download the results generated by the code interpreter.

- Enjoy intuitive, code-free interactions by querying your data using natural language.
        """