-- Account level objects:
use role accountadmin;

DROP DATABASE IF EXISTS IMPACT_GENAI;
DROP SECURITY INTEGRATION IF EXISTS snowservices_ingress_oauth;
DROP ROLE IF EXISTS container_service_role;
DROP WAREHOUSE IF EXISTS GENAI_WH;
DROP COMPUTE POOL IF EXISTS GENAI_COMPUTE_POOL;
DROP ROLE IF EXISTS GENAI_POC_USERS;